# Generated by Django 5.1.2 on 2024-10-14 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
